### ISSUE TITLE
Ajustes no texto sobre autonomia.

### ISSUE THREAD

**Issue by italomen** [cuducos/cuducos.me#1]
Opa! Daê, Cuducos!

Curti a proposta do teu texto :) e tomei a liberdade de sugerir algumas correções por aqui mesmo, beleza?

Ajuste 1 -
"o Cabral, a gente **falaca** sobre..."

Ajuste 2 -
"ou seja, você **não** pode acabar não fazendo o que você queria fazer."
- Comentário:
  Esse "não" inicial parece estar sobrando, e confunde a conclusão da frase. Era esse o objetivo?

Ajuste 3 -
"Muitas vezes vejo pessoas que já **consequem**..."

Ajuste 4 -
"em projetos fodas, **colaboraticos**..."

Esses foram os que saltaram aos olhos.

Abraço!

Ítalo

**Comment by cuducos** [comment]
Bah… valeu, @italomen! Corrigido no 7b11bb1 : )
