### ISSUE TITLE
Ajustes no CSS

### ISSUE THREAD

**Issue by cuducos** [cuducos/cuducos.me#14]
**Bug em dispositivos móveis**

- [ ] Entender se essa gambiarra 0f022daf0be6882b39b1f058cc3eff3e3ddbf72a faz sentido (provavelmente não), e, caso negativo implementar maneira melhor para não quebrar o layout em celulares

---

**Tipografia** — [Post dos exemplos](https://cuducos.me/2016/09/17/porque-elm.html)

- [ ] Em parágrafos, a fonte dos links fica menor do que a do restante do parágrafo

![Pasted_Image_2021-12-08__4_07_PM](https://user-images.githubusercontent.com/4732915/145284547-987f6133-9b47-4d77-8d6d-8e4424b6a8c3.png)
_Nesse exemplo, o parágrafo é renderizado com 20px e o link, com 18px_

- [ ] Blocos de citação não tem diferenciação visual

![Pasted_Image_2021-12-08__4_09_PM](https://user-images.githubusercontent.com/4732915/145284772-9b9751de-0d92-428d-88a7-a03102b9531f.png)
_Esse primeiro parágrafo é um `<blockquote>` e poderia ter alguma diferenciação como margem, fonte diferente, espaçamento, etc._

- [ ] Blocos de citação utilizados para reproduzir tuítes não aparecem com diferencial algum do texto principal, e a arroba do autor do tuíte aparece com a fonte dos títulos

![image](https://user-images.githubusercontent.com/4732915/145285909-25f7dc19-4bcf-46df-9d63-e6f8ec3a8f64.png)

- [ ] Em blocos de “código” (fonte mono-espaçada) a margem para o parágrafo anterior é maior do que a margem para o parágrafo seguinte

![Pasted_Image_2021-12-08__4_12_PM](https://user-images.githubusercontent.com/4732915/145285226-88313318-5e08-48de-bb19-50de855cb2b4.png)
_Nesse exemplo, a é maior que b_

- [ ] Em listas, há muita variação de fonte e espaçamento:
    * Listas ordenadas e não-ordenadas não tem margem para o parágrafo anterior
    * O uso de links em itens da lista dá diferença no tamanho da fonte e na altura da linha (`line-height`)
    * Idem para o uso de fonte mono-espaçada no meio do texto de um item da lista
    * Listas ordenadas não aparecem com numeração
    * Listas não-ordenadas não aparecem com “bullets”
     
![image](https://user-images.githubusercontent.com/4732915/145285487-83919e26-c12a-45a7-a8be-ccd09c7ca8af.png)
_Nesse exemplo temos uma lista ordenada_

![image](https://user-images.githubusercontent.com/4732915/145286061-9659a48d-c84f-421f-a9d0-e06c9fdd5401.png)
_Nesse exemplo temos uma lista não-ordenada_

- [ ] Uso de itálico nos títulos muda a fonte do trecho em itálico
- [ ] Títulos `h4` ou menores estão muito pequenos, difíceis de ler

![image](https://user-images.githubusercontent.com/4732915/145286480-3ef0da66-a853-422c-b50e-63288b0dc7b4.png)

**Comment by rhayana-b** [comment]
> Entender se essa gambiarra 0f022da faz sentido (provavelmente não), e, caso negativo implementar maneira melhor para não quebrar o layout em celulares.

(Fez sim, já até subiu né?) Show!

**Comment by cuducos** [comment]
Closed by #15
